parameters:
    darvin_file.url_builder.builder.class: Darvin\FileBundle\UrlBuilder\UrlBuilder

    darvin_file.url_builder.twig.extension.class: Darvin\FileBundle\Twig\Extension\UrlBuilderExtension

    darvin_file.url_builder.url_absolutizer.class: Darvin\FileBundle\UrlBuilder\UrlAbsolutizer

services:
    Darvin\FileBundle\UrlBuilder\UrlBuilderInterface: '@darvin_file.url_builder.builder'

    darvin_file.url_builder.builder:
        class: '%darvin_file.url_builder.builder.class%'
        arguments:
            - '@vich_uploader.storage'
            - '@darvin_file.url_builder.url_absolutizer'

    darvin_file.url_builder.twig.extension:
        class: '%darvin_file.url_builder.twig.extension.class%'
        arguments:
            - '@darvin_file.url_builder.builder'
        tags:
            - { name: twig.extension }

    darvin_file.url_builder.url_absolutizer:
        class: '%darvin_file.url_builder.url_absolutizer.class%'
        arguments:
            - '@request_stack'
