parameters:
    darvin_file.archive.controller.build.class: Darvin\FileBundle\Controller\Archive\BuildController

    darvin_file.archive.controller.download.class: Darvin\FileBundle\Controller\Archive\DownloadController

    darvin_file.archive.form_factory.class: Darvin\FileBundle\Form\Factory\ArchiveFormFactory

services:
    darvin_file.archive.controller.build:
        class: '%darvin_file.archive.controller.build.class%'
        arguments:
            - '@darvin_file.archiver'
            - '@darvin_utils.flash.notifier'
            - '@darvin_file.archive.form_factory'
            - '@router'
            - '@translator'
        tags:
            - { name: controller.service_arguments }

    darvin_file.archive.controller.download:
        class: '%darvin_file.archive.controller.download.class%'
        arguments:
            - '@darvin_file.archiver'
        tags:
            - { name: controller.service_arguments }

    darvin_file.archive.form_factory:
        class: '%darvin_file.archive.form_factory.class%'
        arguments:
            - '@form.factory'
            - '@router'
