vich_uploader:
    db_driver: orm
    mappings:
        darvin_file:
            uri_prefix:         '/%file_path%'
            upload_destination: '%kernel.project_dir%/public/%file_path%'
            directory_namer:    darvin_file.namer.directory
            namer:              darvin_file.namer.file
